behaviors:
  FlappyBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 4096
      learning_rate: 5.0e-4
      epsilon: 0.25
      beta: 5.0e-3
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 3
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true